hydra:
  run:
    dir: ./hydra_output/${log_folder_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
n_scenarios: 5
log_folder_name: ${model_constructor}
model_constructor: sS_PyomoModelConstructor
model_constructor_params:
  t_max: 30
  a_max: 3
  initial_inventory:
    '1': 0
    '2': 36
  fixed_order_cost: 225
  variable_order_cost: 650
  holding_cost: 130
  emergency_procurement_cost: 3250
  wastage_cost: 650
  M: 100
  additional_fifo_constraints: True
  weekly_policy: False
demand_provider: PoissonDemandProviderSR
solver_string: gurobi_persistent
solver_options:
  LogFile: "gurobi.log"
  OutputFlag: 1
  LogToConsole: 0