hydra:
  run:
    dir: ./hydra_output/${now:%Y-%m-%d}/${now:%H-%M-%S}
t_max: 30
a_max: 3
n_scenarios: 5
model_constructor: sS_PyomoModelConstructor
demand_provider: PoissonDemandProviderSR
solver_string: gurobi_persistent
solver_options:
  LogFile: "gurobi.log"
  OutputFlag: 1
  LogToConsole: 0