min_demands: [0,0,0,0,0,0,0]
max_demands: [60,60,60,60,60,60,60]
mean_demands: [37.5, 37.3, 39.2, 37.8, 40.5, 27.2, 28.4]
gamma: 1.0
max_order: 60
shelf_life_at_arrival_dist: [0, 0, 1]
cost_dict:
  fixed_order_cost: 225
  variable_order_cost: 650
  holding_cost: 130
  emergency_procurement_cost: 3250
  wastage_cost: 650
max_iterations: 20
convergence_test:
  periodic: True
  epsilon: 0.005
batch_size: 13000
save_qvalues_each_iteration: True