hydra:
  run:
    dir: .
  output_subdir: ./hydra_output/${now:%Y-%m-%d}/${now:%H-%M-%S}
hydra_logdir: ${hydra:output_subdir}
model:
  n_hidden: [64]
env:
  mean_demand_per_day: 10
  max_order: 30
  max_age: 5
  transit_time: 2
  env_seed: 5
training:
  device: "cpu"
  gamma: 0.99
  batch_size: 32
  replay_size: 10000
  replay_start_size: 10000
  learning_rate: 1e-4
  sync_target_timesteps: 1000
  epsilon_decay_last_timestep: 150000
  epsilon_start: 1.0
  epsilon_final: 0.01
  total_years: 200
  seed: 15
